# Generated by Django 5.2.1 on 2025-05-22 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название перекрестка')),
                ('location', models.CharField(max_length=200, verbose_name='Расположение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Перекресток',
                'verbose_name_plural': 'Перекрестки',
            },
        ),
        migrations.CreateModel(
            name='TrafficLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('maintenance', 'На обслуживании')], default='inactive', max_length=20, verbose_name='Статус')),
                ('installation_date', models.DateField(verbose_name='Дата установки')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Последнее обслуживание')),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_control.intersection', verbose_name='Перекресток')),
            ],
            options={
                'verbose_name': 'Светофор',
                'verbose_name_plural': 'Светофоры',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Дата обслуживания')),
                ('description', models.TextField(verbose_name='Описание работ')),
                ('technician', models.CharField(max_length=100, verbose_name='Техник')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('traffic_light', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_control.trafficlight', verbose_name='Светофор')),
            ],
            options={
                'verbose_name': 'Запись об обслуживании',
                'verbose_name_plural': 'Записи об обслуживании',
            },
        ),
        migrations.CreateModel(
            name='TrafficLightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_on_time', models.DateTimeField(verbose_name='Время включения')),
                ('turn_off_time', models.DateTimeField(blank=True, null=True, verbose_name='Время выключения')),
                ('cars_passed', models.IntegerField(default=0, verbose_name='Количество проехавших автомобилей')),
                ('cars_waiting', models.IntegerField(default=0, verbose_name='Количество автомобилей в ожидании')),
                ('traffic_light', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_control.trafficlight', verbose_name='Светофор')),
            ],
            options={
                'verbose_name': 'История светофора',
                'verbose_name_plural': 'История светофоров',
            },
        ),
        migrations.CreateModel(
            name='TrafficStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('total_cars', models.IntegerField(default=0, verbose_name='Всего автомобилей')),
                ('peak_hour', models.TimeField(verbose_name='Час пик')),
                ('average_wait_time', models.IntegerField(verbose_name='Среднее время ожидания (сек)')),
                ('traffic_light', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_control.trafficlight', verbose_name='Светофор')),
            ],
            options={
                'verbose_name': 'Статистика движения',
                'verbose_name_plural': 'Статистика движения',
            },
        ),
    ]
